---
storage:
  driver:
    message:
      compression: none
  net:
    sndBuf: 131072
    rcvBuf: 32768
    linger: 0
    tcpNoDelay: true
    timeoutMilliSec: 0
    node:
      addrs:
        - 127.0.0.1
      port: 9092
