---
storage:
  driver:
    create:
      batch:
        enabled: true
        delayMicros: 1000
      compression: none
      timestamp: false
    read:
      tail: false
  net:
    tcpNoDelay: true
    timeoutMilliSec: 0
    node:
      addrs:
        - 127.0.0.1
      port: 6650
