---
storage:
  driver:
    create:
      batch:
        enabled: boolean
        delayMicros: long
      compression: string
      timestamp: boolean
    read:
      tail: boolean
  net:
    tcpNoDelay: boolean
    timeoutMilliSec: int
    node:
      addrs: list
      port: int
