---
storage:
  driver:
    message:
      compression: string
  net:
    sndBuf: int
    rcvBuf: int
    linger: int
    tcpNoDelay: boolean
    timeoutMilliSec: int
    node:
      addrs: list
      port: int
